load_data_fn: load_Cartesian_all
load_coord_fn: load_Cartesian_coord

save_path: ConditionalNeuralField/output_Cartesian/
save_every: ConditionalNeuralField/output_Cartesian/
ckpt_loading_path: ConditionalNeuralField/output_Cartesian/

lumped_latent: False

normalizer:
  method: '-11'
  dim: 0
batch_size: 500
test_batch_size: 0

multiGPU: 6
gpu_id: "0, 1, 2, 3, 4, 5"
master_port: "12365"

readin_data_shape: "N t h w c"
batch_shape: "(N t) h w c"

hidden_size: 256
epochs: 5000

loss_fn: MSELoss
test_criteria: RMSE
save_every: 500
plot_every: 10

dims: 2

log_tag: cartesian_NF
neptune_project: YourNeptuneProjectName
neptune_api_token: YourNeptuneAPIToken


NF:
  name: SIRENAutodecoder_mdf_film
  kwargs:
    omega_0: 5
    in_coord_features: 2
    in_latent_features: 256
    out_features: 3
    num_hidden_layers: 5
    hidden_features: 128

lr:
# -4 -5
  nf: 1.e-4
  latents: 1.e-3