# ---- dataset parameters ----
latent_checkpoint_path: "ConditionalNeuralField/output_topography_unstructured/your_cnf_field_ckpt"
batch_size: 16
test_batch_size: 16

time_length: 128
latent_length: 384

# ---- unet parameters ----
image_size: 128
num_channels: 64    # base channel count for the model
num_res_blocks: 2    # number of residual blocks per downsample
num_heads: 8    # the number of attention heads in each attention layer
num_head_channels: 32    # if specified, ignore num_heads and instead use a fixed channel width per attention head
attention_resolutions: "32,16,8"
channel_mult: "1,1,2,2,4,4"    # channel multiplier for each level of the UNet

# ---- training ----
microbatch: -1
lr : 5.e-5
ema_rate: "0.9999"
log_interval: 100
save_interval: 10000
lr_anneal_steps: 0
steps: 1000
noise_schedule: "cosine"

# ---- logging ----
log_path : "UnconditionalDiffusionTraining_and_Generation/output/logs_case3"
neptune_project: "specify your neptune project here"
neptune_api_token: "specify your neptune api token here"
neptune_tag: "Diffusion_case3"
